// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxedX8JChe1gBuxxwBh1GEX_eEG45pdcQ',
    appId: '1:726676382628:web:162973b4f105cf98179731',
    messagingSenderId: '726676382628',
    projectId: 'notes-de27b',
    authDomain: 'notes-de27b.firebaseapp.com',
    storageBucket: 'notes-de27b.firebasestorage.app',
    measurementId: 'G-CX3B7WLVG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeZOhVvheml5jWsmCpXeO3IFYwbdFm388',
    appId: '1:726676382628:android:695a56536155de86179731',
    messagingSenderId: '726676382628',
    projectId: 'notes-de27b',
    storageBucket: 'notes-de27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7esce2ZA9ziIWoKV-lDuJII5Ui9z_8zs',
    appId: '1:726676382628:ios:4dd8731629f31d7e179731',
    messagingSenderId: '726676382628',
    projectId: 'notes-de27b',
    storageBucket: 'notes-de27b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7esce2ZA9ziIWoKV-lDuJII5Ui9z_8zs',
    appId: '1:726676382628:ios:4dd8731629f31d7e179731',
    messagingSenderId: '726676382628',
    projectId: 'notes-de27b',
    storageBucket: 'notes-de27b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxedX8JChe1gBuxxwBh1GEX_eEG45pdcQ',
    appId: '1:726676382628:web:941d66af34895d34179731',
    messagingSenderId: '726676382628',
    projectId: 'notes-de27b',
    authDomain: 'notes-de27b.firebaseapp.com',
    storageBucket: 'notes-de27b.firebasestorage.app',
    measurementId: 'G-39CQ50EQST',
  );
}
